etl:
  extract:
    input_files:
      - "<path to data>/data/micro_user.csv"
      - "<path to data>/data/stagnant_data.csv"
  transform:
    drop_na: true
    filter:
      column: "age"
      min_value: 18
    rename_columns:
      name: "full_name"
  load:
    output_file: "<path to data>/data/output.csv"
